name: Go CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Build executables
        run: |
          mkdir -p bin
          go build -o ./bin/backtest ./test/backtest
          go build -o ./bin/ctraderapi ./test/ctraderapi
          go build -o ./bin/montecarlo ./test/montecarlo

      - name: Verify executables
        run: |
          test -f ./bin/backtest && echo "backtest exists"
          test -f ./bin/ctraderapi && echo "ctraderapi exists"
          test -f ./bin/montecarlo && echo "montecarlo exists"

      - name: Test Monte Carlo Simulation
        run: ./bin/montecarlo
